version: '3.8'
services:
    postgres:                                           
        image: postgres
        hostname: postgresql
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow

    scheduler:
        image: apache/airflow:2.5.3
        command: scheduler
        depends_on:
            - postgres
        env_file:
            - .env
        volumes:
            - ./dags:/opt/airflow/dags
            - ./logs:/opt/airflow/logs
            - ./csv:/opt/airflow/csv
        
    webserver:
        image: apache/airflow:2.5.3
        entrypoint: ./scripts/entrypoint.sh
        depends_on:
            - postgres
            - scheduler
        env_file:
            - .env
        volumes:
            - ./dags:/opt/airflow/dags
            - ./logs:/opt/airflow/logs
            - ./scripts:/opt/airflow/scripts
        ports:
            - "8080:8080"